### ISSUE TITLE
Initializer fails after latest 7.0.0-SNAPSHOT due to "userStoreKey" not found

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-superhero-blog#23]
2019-01-21 10:30:01,160 ERROR com.enonic.app.superhero - [com.enonic.xp.demo.initializer.DemoInitializer(259)] Error during instantiation of the implementation object
java.lang.NoClassDefFoundError: com/enonic/xp/security/UserStoreKey
	at com.enonic.xp.demo.initializer.DemoInitializer.<clinit>(DemoInitializer.java:61)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

**Comment by alansemenov** [comment]
New version 2.0.1 on the Market should solve this
